#!/bin/bash

# Copyright Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
# or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at 
# https://threatcode.net/license; you may not use this file except in compliance with the
# Elastic License 2.0.



. /usr/sbin/tc-common

rm -f /opt/tc/conf/soc/salt/pipe
pkill salt-relay.sh
/usr/sbin/so-restart soc $1
