#!/bin/bash
#


. /usr/sbin/tc-common
{% set BACKUPLOCATIONS = salt['pillar.get']('backup:locations', {}) %}

TODAY=$(date '+%Y_%m_%d')
BACKUPFILE="/nsm/backup/tc-config-backup-$TODAY.tar"
MAXBACKUPS=7

# Create backup dir if it does not exist
mkdir -p /nsm/backup

# If we haven't already written a backup file for today, let's do so
if [ ! -f $BACKUPFILE ]; then

  # Create empty backup file
  tar -cf $BACKUPFILE -T /dev/null

  # Loop through all paths defined in global.sls, and append them to backup file
  {%- for LOCATION in BACKUPLOCATIONS %}
  tar -rf $BACKUPFILE {{ LOCATION }}
  {%- endfor %}
  tar -rf $BACKUPFILE /etc/pki
  tar -rf $BACKUPFILE /etc/salt
  tar -rf $BACKUPFILE /nsm/kratos

fi

# Find oldest backup files and remove them
NUMBACKUPS=$(find /nsm/backup/ -type f -name "tc-config-backup*" | wc -l)
while [ "$NUMBACKUPS" -gt "$MAXBACKUPS" ]; do
  OLDESTBACKUP=$(find /nsm/backup/ -type f -name "tc-config-backup*" -type f -printf '%T+ %p\n' | sort | head -n 1 | awk -F" " '{print $2}')
  rm -f $OLDESTBACKUP
  NUMBACKUPS=$(find /nsm/backup/ -type f -name "tc-config-backup*" | wc -l)
done
