#!/bin/bash
#

{%- set NODEIP = salt['pillar.get']('elasticsearch:mainip', '') %}
. /usr/sbin/tc-common
if [ "$1" == "" ]; then
    {{ ELASTICCURL }} -s -k -L https://{{ NODEIP }}:9200/_component_template | jq '.component_templates[] |.name'| sort
else
    {{ ELASTICCURL }} -s -k -L https://{{ NODEIP }}:9200/_component_template/$1 | jq
fi
