#!/bin/bash
#

{%- set NODEIP = salt['pillar.get']('elasticsearch:mainip', '') %}
. /usr/sbin/tc-common
if [ "$1" == "" ]; then
    {{ ELASTICCURL }} -s -k -L https://{{ NODEIP }}:9200/_template/* | jq 'keys'
else
    {{ ELASTICCURL }} -s -k -L https://{{ NODEIP }}:9200/_template/$1 | jq
fi
