#!/bin/bash



. /usr/sbin/tc-common


{%- if grains['role'] in ['tc-eval','tc-manager', 'tc-managersearch', 'tc-standalone', 'tc-heavynode', 'tc-node', 'tc-import']%}
/usr/sbin/tc-start elasticsearch $1
{%- endif %}

{%- if grains['role'] in ['tc-eval', 'tc-manager', 'tc-managersearch', 'tc-standalone', 'tc-import']%}
/usr/sbin/tc-start kibana $1
{%- endif %}

{%- if grains['role'] in ['tc-manager', 'tc-managersearch', 'tc-standalone', 'tc-heavynode', 'tc-node']%}
/usr/sbin/tc-start logstash $1
{%- endif %}

{%- if grains['role'] in ['tc-manager', 'tc-managersearch', 'tc-standalone', 'tc-heavynode', 'tc-node', 'tc-sensor']%}
/usr/sbin/tc-start filebeat $1
{%- endif %}

{%- if grains['role'] in ['tc-manager', 'tc-managersearch', 'tc-standalone', 'tc-heavynode', 'tc-node']%}
/usr/sbin/tc-start curator $1
{%- endif %}

{%- if grains['role'] in ['tc-eval','tc-manager', 'tc-managersearch', 'tc-standalone']%}
/usr/sbin/tc-start elastalert $1
{%- endif %}
