#!/bin/bash



. /usr/sbin/tc-common


{%- if grains['role'] in ['tc-eval','tc-manager', 'tc-managersearch', 'tc-standalone', 'tc-heavynode', 'tc-node', 'tc-import']%}
/usr/sbin/tc-stop elasticsearch $1
{%- endif %}

{%- if grains['role'] in ['tc-eval', 'tc-manager', 'tc-managersearch', 'tc-standalone', 'tc-import']%}
/usr/sbin/tc-stop kibana $1
{%- endif %}

{%- if grains['role'] in ['tc-manager', 'tc-managersearch', 'tc-standalone', 'tc-heavynode', 'tc-node']%}
/usr/sbin/tc-stop logstash $1
{%- endif %}

{%- if grains['role'] in ['tc-manager', 'tc-managersearch', 'tc-standalone', 'tc-heavynode', 'tc-node', 'tc-sensor']%}
/usr/sbin/tc-stop filebeat $1
{%- endif %}

{%- if grains['role'] in ['tc-manager', 'tc-managersearch', 'tc-standalone', 'tc-heavynode', 'tc-node']%}
/usr/sbin/tc-stop curator $1
{%- endif %}

{%- if grains['role'] in ['tc-eval','tc-manager', 'tc-managersearch', 'tc-standalone']%}
/usr/sbin/tc-stop elastalert $1
{%- endif %}
