#!/bin/bash
#

{%- set NODEIP = salt['pillar.get']('elasticsearch:mainip', '') %}
. /usr/sbin/tc-common

SKIP=0
#########################################
# Options
#########################################
usage()
{
cat <<EOF
Threat Code Elastic Clear
  Options:
  -h         This message
  -y         Skip interactive mode
EOF
}
while getopts "h:y" OPTION
do
        case $OPTION in
                h)
                        usage
                        exit 0
                        ;;
                
                y)
                        SKIP=1
                        ;;
                *)
                        usage
                        exit 0
                        ;;
        esac
done
if [ $SKIP -ne 1 ]; then
        # List indices
        echo 
        {{ ELASTICCURL }} -k -L https://{{ NODEIP }}:9200/_cat/indices?v
        echo
        # Inform user we are about to delete all data
        echo
        echo "This script will delete all data (documents, indices, etc.) in the Elasticsearch database."
        echo
        echo "If you would like to proceed, please type "AGREE" and hit ENTER."
        echo
        # Read user input
        read INPUT
        if [ "$INPUT" != "AGREE" ] ; then exit 0; fi
fi

# Check to see if Logstash/Filebeat are running
LS_ENABLED=$(tc-status | grep logstash)
FB_ENABLED=$(tc-status | grep filebeat)
EA_ENABLED=$(tc-status | grep elastalert)

if [ ! -z "$FB_ENABLED" ]; then

        /usr/sbin/tc-filebeat-stop

fi

if [ ! -z "$LS_ENABLED" ]; then

        /usr/sbin/tc-logstash-stop

fi

if [ ! -z "$EA_ENABLED" ]; then

        /usr/sbin/tc-elastalert-stop

fi

# Delete data
echo "Deleting data..."

INDXS=$({{ ELASTICCURL }} -s -XGET -k -L https://{{ NODEIP }}:9200/_cat/indices?v | egrep 'logstash|elastalert|tc-' | awk '{ print $3 }')
for INDX in ${INDXS}
do
    {{ ELASTICCURL }} -XDELETE -k -L https://"{{ NODEIP }}:9200/${INDX}" > /dev/null 2>&1
done

#Start Logstash/Filebeat
if [ ! -z "$FB_ENABLED" ]; then

        /usr/sbin/tc-filebeat-start

fi

if [ ! -z "$LS_ENABLED" ]; then

        /usr/sbin/tc-logstash-start

fi

if [ ! -z "$EA_ENABLED" ]; then

        /usr/sbin/tc-elastalert-start

fi

