#!/bin/bash
#


. /usr/sbin/tc-common

usage() {
    echo "Usage: $0 <new-user-email>"
    echo ""
    echo "Adds a new user to Fleet. The new password will be read from STDIN."
    exit 1
}

if [ $# -ne 1 ]; then
  usage
fi


USER_EMAIL=$1
FLEET_SA_EMAIL=$(lookup_pillar_secret fleet_sa_email)
FLEET_SA_PW=$(lookup_pillar_secret fleet_sa_password)
MYSQL_PW=$(lookup_pillar_secret mysql)

# Read password for new user from stdin
test -t 0
if [[ $? == 0 ]]; then
  echo "Enter new password:"
fi
read -rs USER_PASS

check_password_and_exit "$USER_PASS"

# Config fleetctl & login with the TC Service Account
CONFIG_OUTPUT=$(docker exec tc-fleet fleetctl config set --address https://127.0.0.1:8080 --tls-skip-verify --url-prefix /fleet  2>&1 )
SALOGIN_OUTPUT=$(docker exec tc-fleet fleetctl login --email $FLEET_SA_EMAIL --password $FLEET_SA_PW 2>&1)

if [[ $? -ne 0 ]]; then
    echo "Unable to add user to Fleet; Fleet Service account login failed"
    echo "$SALOGIN_OUTPUT"
    exit 2
fi

TEMPPW=$FLEET_SA_PW!

# Create New User
CREATE_OUTPUT=$(docker exec tc-fleet fleetctl user create --email $USER_EMAIL --name $USER_EMAIL --password $TEMPPW --global-role admin 2>&1)

if [[ $? -eq 0 ]]; then
    echo "Successfully added user to Fleet"
else
    echo "Unable to add user to Fleet; user might already exist"
    echo "$CREATE_OUTPUT"
    exit 2
fi

# Reset New User Password to user supplied password
echo "$USER_PASS" | tc-fleet-user-update "$USER_EMAIL"

# Disable forced password reset
MYSQL_OUTPUT=$(docker exec tc-mysql mysql -u root --password=$MYSQL_PW fleet -e \
"UPDATE users SET admin_forced_password_reset = 0 WHERE email = '$USER_EMAIL'" 2>&1)
