#!/bin/bash
#


. /usr/sbin/tc-common

usage() {
    echo "Usage: $0 <user-email>"
    echo ""
    echo "Deletes a user in Fleet"
    exit 1
}

if [ $# -ne 1 ]; then
  usage
fi

USER_EMAIL=$1
FLEET_SA_EMAIL=$(lookup_pillar_secret fleet_sa_email)
FLEET_SA_PW=$(lookup_pillar_secret fleet_sa_password)

# Config fleetctl & login with the SO Service Account
CONFIG_OUTPUT=$(docker exec tc-fleet fleetctl config set --address https://127.0.0.1:8080 --tls-skip-verify --url-prefix /fleet  2>&1 )
SALOGIN_OUTPUT=$(docker exec tc-fleet fleetctl login --email $FLEET_SA_EMAIL --password $FLEET_SA_PW 2>&1)

if [[ $? -ne 0 ]]; then
    echo "Unable to delete user from Fleet; Fleet Service account login failed"
    echo "$SALOGIN_OUTPUT"
    exit 2
fi

# Delete User
DELETE_OUTPUT=$(docker exec tc-fleet fleetctl user delete --email $USER_EMAIL 2>&1)

if [[ $? -eq 0 ]]; then
    echo "Successfully deleted user from Fleet"
else
    echo "Unable to delete user from Fleet"
    echo "$DELETE_OUTPUT"
    exit 2
fi


