#!/bin/bash
#


if [ $# -lt 2 ]; then
  echo "Usage: $0 <steno-query> Output-Filename"
  exit 1
fi

docker exec -t tc-sensoroni scripts/stenoquery.sh "$1" -w /nsm/pcapout/$2.pcap

echo ""
echo "If successful, the output was written to: /nsm/pcapout/$2.pcap"
