#!/bin/bash



# Usage: tc-start  all | filebeat | kibana | playbook 

. /usr/sbin/tc-common

if [ $# -ge 1 ]; then
	echo $banner
	printf "Starting $1...\n\nThis could take a while if another Salt job is running. \nRun this command with --force to stop all Salt jobs before proceeding.\n"
	echo $banner

	if [ "$2" = "--force" ]; then
   		printf "\nForce-stopping all Salt jobs before proceeding\n\n"
   		salt-call saltutil.kill_all_jobs
	fi

	case $1 in
   		"all") salt-call state.highstate queue=True;;
   		"steno") if docker ps | grep -q tc-$1; then printf "\n$1 is already running!\n\n"; else docker rm tc-$1 >/dev/null 2>&1 ; salt-call state.apply pcap queue=True; fi ;; 
   		*) if docker ps | grep -E -q '^tc-$1$'; then printf "\n$1 is already running\n\n"; else docker rm tc-$1 >/dev/null 2>&1 ; salt-call state.apply $1 queue=True; fi ;; 
	esac
else
	echo -e "\nPlease provide an argument by running like tc-start $component, or by using the component-specific script.\nEx. tc-start filebeat, or tc-filebeat-start\n"	
fi
