#!/bin/bash



# Show Zeek stats (capstats, netstats)

show_stats() {
  echo '##############'
  echo '# Zeek Stats #'
  echo '##############'
  echo
  echo "Average throughput:"
  echo
  docker exec tc-zeek env -i PATH=/bin:/usr/bin:/sbin:/usr/sbin:/opt/bin:/usr/local/bin:/usr/local/sbin /opt/zeek/bin/zeekctl capstats
  echo
  echo "Average packet loss:"
  echo
  docker exec tc-zeek env -i PATH=/bin:/usr/bin:/sbin:/usr/sbin:/opt/bin:/usr/local/bin:/usr/local/sbin /opt/zeek/bin/zeekctl netstats
  echo
}

if docker ps | grep -q zeek; then
  show_stats
else
  echo "Zeek is not running! Try starting it with 'tc-zeek-start'." && exit 1;
fi
